# 교통사고 top5(모두 도로면적 75000 이상)와 면적이 75000 이상인 지역 중 교통사고 수 하위 5곳의 사업체수 비교
- 데이터 : 서울시 사업체현황 (조직형태별/동별) 통계 
https://data.seoul.go.kr/dataList/10608/S/2/datasetView.do
- 한계 : 사업체의 위도,경도가 나와있지 않기 때문에 읍,면,동 데이터를 이용하여 분석

In [ ]:
!pip install geopandas

In [ ]:
!pip install geopandas
!pip install folium matplotlib mapclassify

In [3]:
import pandas as pd

In [4]:
top5 = pd.read_csv('/content/drive/MyDrive/프로젝트1/데이터/top5_grid.csv')
low5 = pd.read_csv('/content/drive/MyDrive/프로젝트1/데이터/low_gangnam.csv')

In [11]:
top5.head()

,gid,geometry,gu
0,다사57b45a,"POLYGON ((957500 1945000, 957500 1945500, 9580...",강남구 서초구
1,다사59a47a,"POLYGON ((959000 1947000, 959000 1947500, 9595...",강남구
2,다사58a44a,"POLYGON ((958000 1944000, 958000 1944500, 9585...",강남구 서초구
3,다사59a44b,"POLYGON ((959000 1944500, 959000 1945000, 9595...",강남구
4,다사58b46a,"POLYGON ((958500 1946000, 958500 1946500, 9590...",강남구

In [13]:
low5.head()

,gid,초등학교수,중학교수,고등학교수,어린이보호구역수,교차로,보행자작동신호기,횡단보도,음향신호기,안전표지,신호등,잔여시간표시기,도로면적,총인구수,단란주점,유흥주점,일반음식점,교통사고수,geometry,gu
0,다사57a46b,0,0,0,0,8.0,2.0,95.0,9.0,186.0,111.0,9.0,75674.335509,22.0,0,0,1,39,"POLYGON ((957000 1946500, 957000 1947000, 9575...",강남구 서초구
1,다사66a42a,0,0,0,0,0.0,0.0,35.0,23.0,48.0,58.0,32.0,79577.977645,0.0,0,0,0,42,"POLYGON ((966000 1942000, 966000 1942500, 9665...",강남구 송파구
2,다사66b41a,0,0,0,0,0.0,0.0,46.0,5.0,126.0,50.0,6.0,107197.509594,0.0,0,0,0,48,"POLYGON ((966500 1941000, 966500 1941500, 9670...",강남구 송파구
3,다사60b47a,0,0,0,0,0.0,0.0,65.0,9.0,257.0,119.0,15.0,75394.201502,3176.0,2,4,95,52,"POLYGON ((960500 1947000, 960500 1947500, 9610...",강남구
4,다사60b45a,0,0,0,0,0.0,0.0,97.0,48.0,307.0,97.0,49.0,76580.818293,3925.0,5,13,305,64,"POLYGON ((960500 1945000, 960500 1945500, 9610...",강남구

## top5 격자지도 데이터 프레임
```
기존에 .shp을 로드해서 csv로 저장했기 때문에 'geometry'열이 존재한다.

그러나 csv로 저장하면서 기존에 'geometry'열의 데이터 타입이 문자열로 변경되었다.

따라서 wkt.loads를 이용해서 문자열 타입을 폴리곤 타입으로 바꾸고, geodataframe을 구성할 때 좌표계 정보(epsg:5179)를 주었다.

```

In [15]:
from shapely import wkt

top5['geometry'] = top5['geometry'].apply(wkt.loads)
top5_grids = gpd.GeoDataFrame(top5, crs='epsg:5179')

TypeError: ignored

In [5]:
top5.head()

,gid,geometry,gu
0,다사57b45a,"POLYGON ((957500 1945000, 957500 1945500, 9580...",강남구 서초구
1,다사59a47a,"POLYGON ((959000 1947000, 959000 1947500, 9595...",강남구
2,다사58a44a,"POLYGON ((958000 1944000, 958000 1944500, 9585...",강남구 서초구
3,다사59a44b,"POLYGON ((959000 1944500, 959000 1945000, 9595...",강남구
4,다사58b46a,"POLYGON ((958500 1946000, 958500 1946500, 9590...",강남구

In [ ]:
top5.explore(tiles='http://mt0.google.com/vt/lyrs=m&hl=ko&x={x}&y={y}&z={z}', attr='Google')

In [6]:
low5.head()

,gid,초등학교수,중학교수,고등학교수,어린이보호구역수,교차로,보행자작동신호기,횡단보도,음향신호기,안전표지,신호등,잔여시간표시기,도로면적,총인구수,단란주점,유흥주점,일반음식점,교통사고수,geometry,gu
0,다사57a46b,0,0,0,0,8.0,2.0,95.0,9.0,186.0,111.0,9.0,75674.335509,22.0,0,0,1,39,"POLYGON ((957000 1946500, 957000 1947000, 9575...",강남구 서초구
1,다사66a42a,0,0,0,0,0.0,0.0,35.0,23.0,48.0,58.0,32.0,79577.977645,0.0,0,0,0,42,"POLYGON ((966000 1942000, 966000 1942500, 9665...",강남구 송파구
2,다사66b41a,0,0,0,0,0.0,0.0,46.0,5.0,126.0,50.0,6.0,107197.509594,0.0,0,0,0,48,"POLYGON ((966500 1941000, 966500 1941500, 9670...",강남구 송파구
3,다사60b47a,0,0,0,0,0.0,0.0,65.0,9.0,257.0,119.0,15.0,75394.201502,3176.0,2,4,95,52,"POLYGON ((960500 1947000, 960500 1947500, 9610...",강남구
4,다사60b45a,0,0,0,0,0.0,0.0,97.0,48.0,307.0,97.0,49.0,76580.818293,3925.0,5,13,305,64,"POLYGON ((960500 1945000, 960500 1945500, 9610...",강남구

In [ ]:
saup = pd.read_csv('/content/drive/MyDrive/프로젝트1/데이터/사업체/사업체현황(조직형태별_동별)_20230116160326.csv',
                   header = 1)

In [ ]:
saup.head(20)

In [ ]:
saup[['동별(1)','동별(2)','동별(3)','합계','합계.2']]

     동별(1)  동별(2)  동별(3)       합계     합계.2
0    동별(1)  동별(2)  동별(3)     사업체수     종사자수
1    동별(1)  동별(2)  동별(3)     사업체수       소계
2       합계     소계     소계  1211053  5868926
3       합계    종로구     소계    50531   284570
4       합계    종로구    사직동     5221    53401
..     ...    ...    ...      ...      ...
448     합계    강동구   둔촌1동       39      301
449     합계    강동구   둔촌2동     2164    10483
450     합계    강동구   암사1동     2754     6396
451     합계    강동구   천호2동     4896    14506
452     합계    강동구     길동     5933    24713

[453 rows x 5 columns]