- traffic_time_by_grid : 잔여시간표시기
- traffic_light_by_grid : 신호등
- crosswalk_by_grid : 횡단보도
- geo_acoustic_by_grid : 음향신호기
- geo_safety_by_grid : 안전표지
- pedestrian_by_grid : 보행자작동신호기 
- crossroad_by_grid : 교차로

In [1]:
import pandas as pd

In [19]:
crossroad_by_grid = pd.read_csv('/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/crossroad_by_grid')
pedestrian_by_grid = pd.read_csv('/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/pedestrian_by_grid')

df1 = pd.merge(crossroad_by_grid, pedestrian_by_grid, on='gid')
df1.head()

        gid  교차로코드  보행자작동신호기 관리번호
0  다사38a53a      3              1
1  다사39a51b      7              2
2  다사39a52b      7              4
3  다사39a53a     14              2
4  다사39b51b      5              6

In [20]:
import glob
csvs = glob.glob('/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/*grid')[:]
csvs.sort()
csvs

['/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/crossroad_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/crosswalk_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_acoustic_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_safety_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/pedestrian_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_light_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_time_by_grid']

In [21]:
import glob
csvs = glob.glob('/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/*grid')[2:]
csvs.sort()
csvs

['/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/crosswalk_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_acoustic_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_safety_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_light_by_grid',
 '/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_time_by_grid']

In [22]:
# 시설물 파일 통합하여 하나의 데이터 프레임 생성
dfs = pd.DataFrame(df1)
for csv in csvs:
  print( csv )
  df = pd.read_csv(csv, encoding='utf-8')
  dfs = pd.merge(dfs, df, how='outer', on='gid')
  display( dfs )

/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/crosswalk_by_grid

           gid  교차로코드  보행자작동신호기 관리번호  횡단보도관리번호
0     다사38a53a    3.0            1.0        39
1     다사39a51b    7.0            2.0        63
2     다사39a52b    7.0            4.0        97
3     다사39a53a   14.0            2.0       103
4     다사39b51b    5.0            6.0        97
...        ...    ...            ...       ...
1901  다사71b50a    NaN            NaN         7
1902  다사71b50b    NaN            NaN         3
1903  다사71b51a    NaN            NaN       100
1904  다사71b51b    NaN            NaN       172
1905  다사72a50a    NaN            NaN        24

[1906 rows x 4 columns]

/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_acoustic_by_grid

           gid  교차로코드  보행자작동신호기 관리번호  횡단보도관리번호  음향신호관리번호
0     다사38a53a    3.0            1.0      39.0       6.0
1     다사39a51b    7.0            2.0      63.0      10.0
2     다사39a52b    7.0            4.0      97.0      16.0
3     다사39a53a   14.0            2.0     103.0      20.0
4     다사39b51b    5.0            6.0      97.0      21.0
...        ...    ...            ...       ...       ...
1906  다사48b49a    NaN            NaN       NaN       2.0
1907  다사54b47a    NaN            NaN       NaN       1.0
1908  다사60a43b    NaN            NaN       NaN       1.0
1909  다사60a59b    NaN            NaN       NaN       1.0
1910  다사69a51b    NaN            NaN       NaN       1.0

[1911 rows x 5 columns]

/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/geo_safety_by_grid

           gid  교차로코드  보행자작동신호기 관리번호  횡단보도관리번호  음향신호관리번호  안전표지관리번호
0     다사38a53a    3.0            1.0      39.0       6.0      97.0
1     다사39a51b    7.0            2.0      63.0      10.0     164.0
2     다사39a52b    7.0            4.0      97.0      16.0     218.0
3     다사39a53a   14.0            2.0     103.0      20.0     150.0
4     다사39b51b    5.0            6.0      97.0      21.0     174.0
...        ...    ...            ...       ...       ...       ...
2088  다사69b52a    NaN            NaN       NaN       NaN      18.0
2089  다사70a52a    NaN            NaN       NaN       NaN       2.0
2090  다사70a52b    NaN            NaN       NaN       NaN      17.0
2091  다사71a53a    NaN            NaN       NaN       NaN       5.0
2092  다사71b49b    NaN            NaN       NaN       NaN      19.0

[2093 rows x 6 columns]

/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_light_by_grid

           gid  교차로코드  보행자작동신호기 관리번호  횡단보도관리번호  음향신호관리번호  안전표지관리번호  신호등관리번호
0     다사38a53a    3.0            1.0      39.0       6.0      97.0     17.0
1     다사39a51b    7.0            2.0      63.0      10.0     164.0     45.0
2     다사39a52b    7.0            4.0      97.0      16.0     218.0     96.0
3     다사39a53a   14.0            2.0     103.0      20.0     150.0    213.0
4     다사39b51b    5.0            6.0      97.0      21.0     174.0     68.0
...        ...    ...            ...       ...       ...       ...      ...
2089  다사70a52a    NaN            NaN       NaN       NaN       2.0      4.0
2090  다사70a52b    NaN            NaN       NaN       NaN      17.0      NaN
2091  다사71a53a    NaN            NaN       NaN       NaN       5.0      NaN
2092  다사71b49b    NaN            NaN       NaN       NaN      19.0      4.0
2093  다사37b49a    NaN            NaN       NaN       NaN       NaN      1.0

[2094 rows x 7 columns]

/content/drive/MyDrive/프로젝트1/데이터/도로시설물_정제데이터/traffic_time_by_grid

,gid,교차로코드,보행자작동신호기 관리번호,횡단보도관리번호,음향신호관리번호,안전표지관리번호,신호등관리번호,잔여표시 관리번호
0,다사38a53a,3.0,1.0,39.0,6.0,97.0,17.0,2.0
1,다사39a51b,7.0,2.0,63.0,10.0,164.0,45.0,10.0
2,다사39a52b,7.0,4.0,97.0,16.0,218.0,96.0,NaN
3,다사39a53a,14.0,2.0,103.0,20.0,150.0,213.0,23.0
4,다사39b51b,5.0,6.0,97.0,21.0,174.0,68.0,26.0
...,...,...,...,...,...,...,...,...
2090,다사70a52b,NaN,NaN,NaN,NaN,17.0,NaN,NaN
2091,다사71a53a,NaN,NaN,NaN,NaN,5.0,NaN,NaN
2092,다사71b49b,NaN,NaN,NaN,NaN,19.0,4.0,NaN
2093,다사37b49a,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2094,다사47b58b,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [23]:
dfs = dfs.fillna(0)

In [24]:
dfs.shape

(2095, 8)

In [27]:
dfs.head(10)

,gid,교차로코드,보행자작동신호기 관리번호,횡단보도관리번호,음향신호관리번호,안전표지관리번호,신호등관리번호,잔여표시 관리번호
0,다사38a53a,3.0,1.0,39.0,6.0,97.0,17.0,2.0
1,다사39a51b,7.0,2.0,63.0,10.0,164.0,45.0,10.0
2,다사39a52b,7.0,4.0,97.0,16.0,218.0,96.0,0.0
3,다사39a53a,14.0,2.0,103.0,20.0,150.0,213.0,23.0
4,다사39b51b,5.0,6.0,97.0,21.0,174.0,68.0,26.0
5,다사39b52a,8.0,7.0,74.0,46.0,199.0,94.0,35.0
6,다사39b52b,9.0,2.0,138.0,24.0,181.0,129.0,18.0
7,다사40a50b,2.0,2.0,30.0,4.0,120.0,36.0,12.0
8,다사40a52b,2.0,3.0,46.0,6.0,118.0,31.0,6.0
9,다사40b44a,6.0,8.0,50.0,0.0,165.0,83.0,1.0

In [31]:
df_facility= dfs.rename(columns={'음향신호관리번호':'음향신호기', '횡단보도관리번호':'횡단보도', '교차로코드':'교차로', '안전표지관리번호':'안전표지',
                    '보행자작동신호기 관리번호':'보행자작동신호기', '신호등관리번호':'신호등', '잔여표시 관리번호':'잔여시간표시기'})
#음향신호관리번호_x':'음향신호관리번호','횡단보도관리번호_x':'횡단보도관리번호'

In [32]:
df_facility.head()

        gid   교차로  보행자작동신호기   횡단보도  음향신호기   안전표지    신호등  잔여시간표시기
0  다사38a53a   3.0       1.0   39.0    6.0   97.0   17.0      2.0
1  다사39a51b   7.0       2.0   63.0   10.0  164.0   45.0     10.0
2  다사39a52b   7.0       4.0   97.0   16.0  218.0   96.0      0.0
3  다사39a53a  14.0       2.0  103.0   20.0  150.0  213.0     23.0
4  다사39b51b   5.0       6.0   97.0   21.0  174.0   68.0     26.0

In [33]:
df_facility.to_csv('df_facility')